name: run-azure-e2e-tests

on:
  workflow_call:
    inputs:
      #TODO how to decide/setup branch/versions etc
      branch:
        description: 'Branch to run tests on'
        required: true
        default: 'main'
        type: string
#      delete-bee:
#        description: 'Delete created bee after running tests'
#        required: true
#        default: true
#        type: boolean
        #TODO: what subjects do we need
#      owner-subject:
#        description: 'Owner subject (used for creating billing project in E2E testing)'
#        required: true
#        default: 'hermione.owner@quality.firecloud.org'
#        type: string
#      student-subjects:
#        description: 'A JSON array of Student subjects used for E2E testing'
#        required: true
#        default: '["harry.potter@quality.firecloud.org","ron.weasley@quality.firecloud.org"]'
#        type: string
#      service-account:
#        description: 'Email address or unique identifier of the Google Cloud service account for which to generate credentials'
#        required: true
#        default: 'firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com'
#        type: string
#      tenant-id:
#        description: 'Azure tenant ID. Set the default tenant ID to match your App deployment on Azure'
#        required: true
#        default: 'fad90753-2022-4456-9b0a-c7e5b934e408'
#        type: string
#      subscription-id:
#        description: 'Azure subscription ID. Set the default subscription ID to match your App deployment on Azure'
#        required: false
#        default: 'f557c728-871d-408c-a28b-eb6b2141a087'
#        type: string
#      mrg-id:
#        description: 'Azure Managed Resource Group name. Set the default MRG to match your App deployment on Azure'
#        required: true
#        default: 'staticTestingMrg'
#        type: string
#      landing-zone-id:
#        description: 'Landing Zone ID. Set the LZID to match your App deployment on Azure'
#        required: true
#        default: 'f41c1a97-179b-4a18-9615-5214d79ba600'
#        type: string
      bee-name:
        description: 'bee name'
        required: true
        type: string
      billing-project-name:
        description: 'name of billing project'
        required: true
        type: string

#    secrets:
#      user-access-token:
#        required: true
#        description: "user bearer access token for terra api access"


env:
  CHECKOUT_PATH: "dsp-reusable-workflows/" # arbitrary folder name to checkout to for organizational purposes
  SCRIPT_PATH: "e2e-test/" # location in the checked-out repo of the script to run
  ARTIFACT_PATH: "test-results/" # arbitrary folder name to download test-results to for organizational purposes
  BEE_NAME: '${{ inputs.bee-name }}'
  BILLING_PROJECT_NAME: '${{ inputs.billing-project-name }}' # github token for access to kick off a job in the private repo
  #AZURE_TOKEN: '${{ secrets.user-access-token }}' # github token for access to kick off a job in the private repo

jobs:
  init-github-context:
    runs-on: ubuntu-latest
#    outputs:
#      branch: ${{ steps.extract-inputs.outputs.branch }}
    steps:
      - name: Get inputs or use defaults
        id: extract-inputs
        run: |
#          echo "owner-subject=${{ inputs.owner-subject              || 'hermione.owner@quality.firecloud.org' }}" >> "$GITHUB_OUTPUT"

  run-e2e-test-job:
    runs-on: ubuntu-latest
    needs: [init-github-context] #, create-bee-workflow, params-gen, attach-landing-zone-to-bee-workflow]
    steps:

      - name: "Checkout dsp-reusable-workflows"
        uses: actions/checkout@v3
        with:
          ref: aj-1287-attempt-workflow-call #${{ inputs.target-branch }}
          repository: broadinstitute/dsp-reusable-workflows
          path: ${{ env.CHECKOUT_PATH }}

      - name: Setup Python # Set Python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 #3.11 is causing problems with the wds client - going back to 3.9 for now

      - name: Install pytest
        run: |
          cd ${{ env.CHECKOUT_PATH }}${{ env.SCRIPT_PATH }}
          pip install -r requirements.txt
          pip install pytest

      - name: 'Obtain OAuth2 2.0 Access Token'
        id: 'obtain-token'
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/1038484894585/locations/global/workloadIdentityPools/github-wi-pool/providers/github-wi-provider'
          service_account: 'firecloud-qa@broad-dsde-qa.iam.gserviceaccount.com'
          access_token_scopes: 'profile, email, openid'
          access_token_subject: 'hermione.owner@quality.firecloud.org'
          export_environment_variables: false 

      - name: Run test
        run: |
          cd ${{ env.CHECKOUT_PATH }}${{ env.SCRIPT_PATH }}
          ls
          which pytest
          AZURE_TOKEN=${{ steps.obtain-token.outputs.access_token }}\
            python e2etest.py #experiment
